title = "青崖间"
baseURL = "https://zhaomingxia.com"
theme = "bilberry-hugo-theme"

enableRobotsTXT = true

# Change to one of your content languages definded at the end.
DefaultContentLanguage = "zh-cn"

# Enable / Disable Google Analytics statistics for your site
# googleAnalytics = ""

# Enable / Disable comments on the articles via Disqus.
# disqusShortname = "bilberry-hugo-theme"

[params]
  # Favicon for the browser's favorites and tabs
  favicon = "" # set a favicon icon

  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = []
  js_modules = []

  # Description and meta data for the search engines
  author = "青崖居士"
  description = "且放白鹿青崖间，须行即骑访名山"
  keywords = "青崖"

  # How many articles should be displayed at once?
  paginate = 7

  # Enable / Disable MathJax
  enable_mathjax    = false

  # Header configuration
    # your subtitle if you want to use any
    subtitle = "且放白鹿青崖间，须行即骑访名山"

    # set an path to the image file you want to use | overwrites gravatar
    customImage = "logo.jpg"

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = false

    # show a language chooser in the header
    showHeaderLanguageChooser = true


  # Footer configuration
    showFooter = true

    # How many articles should be displayed at latest posts in the footer?
    # Set to -1 to hide the 'Latest Posts' column
    amountLatestPostsInFooter = 7

    # How many categories should be displayed in the footer section?
    # Set to -1 to hide the 'Categories' column
    amountCategoriesInFooter = 7

    # show a language chooser in the header
    showFooterLanguageChooser = true

    # social media profile urls for the footer links
    showSocialMedia = true

    facebook   = ""
    twitter    = ""
    googleplus = ""
    pinterest  = ""
    instagram  = ""
    tumblr     = ""
    youtube    = ""
    vimeo      = ""
    github     = ""
    xing       = ""
    linkedin   = ""

    # credits line configuration
    copyrightBy = "By 温泉居士"
    copyrightUseCurrentYear = true  # set to true to always display the current year in the copyright
    copyrightYearOverride = ""
    copyrightUrl = "http://zhaomingxia.com"
    creditsText = "温泉居"
    creditsUrl = "http://zhaomingxia.com"


# customize your available languages for your multi-langual site
# or delete the [Languages] blog to use the theme with only one supported language
[Languages]
  [Languages.zh-cn]
    weight = 1

# don't change anything below
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"

[outputs]
  home = [ "HTML", "JSON", "RSS" ]
  page = [ "HTML" ]

